# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0002_auto_20181023_0443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='identitiy',
            new_name='identity',
        ),
    ]
