# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodie', '0003_auto_20181023_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.CharField(default='example@mail.com', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='neighbor_hood',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoodbus', to='hoodie.nieghbor'),
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL),
        ),
    ]
